export const mockOutput = {
  fullName: 'Ronalds Upenieks',
  country: 'Germany',
  city: 'Berlin',
  address: '',
  email: 'RonaldsUpenieks@gmail.com',
  phoneNumber: '',
  positionName: 'Senior Full Stack Software Engineer',
  experience: [
    {
      positionTitle: 'Software Engineer',
      startDate: '08/2020',
      endDate: 'Present',
      company: 'Casavi',
      contributions: [
        'Contributed to features that now generate nearly EURO 1M ARR.',
        "Led our team to 1st place in the company's AI Hackathon.",
        'Streamlined our workflow by cutting out unnecessary meetings and processes.',
        'Introduced engineering days to enhance knowledge sharing and skills.',
        'Drove the adoption of MaterialUI, bridging the gap between developers and designers.',
        'Worked in-depth with technologies like React, Node, MongoDB, and PostgreSQL.',
        'Coordinated feature planning and execution to meet deadlines.',
        'Led a side project to explore and prototype new AI features.',
        'Aligned team goals using OKRs to align vision and tasks.',
        'Ensured smooth communication between our engineering and business teams.',
      ],
    },
    {
      positionTitle: 'Software Engineer',
      startDate: '02/2019',
      endDate: '08/2020',
      company: 'Trana',
      contributions: [
        'Played a pivotal role in steering product development, working closely with leadership and design teams to refine and achieve product-market fit.',
        'Solely transformed Figma designs into precise frontend components.',
        'Developed APIs using a TDD approach.',
        'Conducted comprehensive front-end tests with Cypress.',
        'Actively spearheaded the hiring process for new engineers.',
        'Mentored a junior team member, guiding their development and ensuring project cohesion.',
      ],
    },
    {
      positionTitle: 'Junior Software Engineer',
      startDate: '04/2018',
      endDate: '10/2018',
      company: 'n8n',
      contributions: [
        'Integrated new features into the product by understanding and dissecting APIs.',
        'Troubleshot API issues and worked with various authentication flows.',
        'Improved user experience by abstracting complex API operations.',
        'Authored extensive documentation to support the user base.',
        'Addressed GitHub issues promptly by fixing bugs and addressing user concerns.',
      ],
    },
    {
      positionTitle: 'Junior Software Engineer',
      startDate: '08/2017',
      endDate: '04/2018',
      company: 'Myos',
      contributions: [
        'Developed, tested, and deployed frontend and backend services in TypeScript.',
        "Constructed an interface for internal team's finance management.",
        'Implemented GraphQL microservices to enhance application functionality.',
        'Managed the deployment of services using Kubernetes.',
        'Utilized GitHub Actions for CI/CD implementation.',
      ],
    },
  ],
  education: [
    {
      university: 'Technological University Dublin',
      degree: 'B.Sc Computer Science International',
      startDate: '2017',
      endDate: '2019',
    },
    {
      university: 'Hochschule Darmstadt',
      degree: 'B.Sc Computer Science',
      startDate: '2016',
      endDate: '2017',
    },
  ],
  skills: [
    'Project Management',
    'React',
    'TypeScript',
    'Node.js',
    'GraphQL',
    'HTML & CSS',
    'JavaScript',
    'Kubernetes',
    'REST API',
    'Docker',
    'NestJS',
    'React Native',
    'Document-DB',
    'Prompt Engineering',
    'OpenAI API',
  ],
  references: [],
};
