export const themes = {
	default: {
		'--background': '#ffffff',
		'--foreground': '#020817',
		'--card': '#ffffff',
		'--card-foreground': '#020817',
		'--popover': '#ffffff',
		'--popover-foreground': '#020817',
		'--primary': '#0f172a',
		'--primary-foreground': '#f8fafc',
		'--secondary': '#f1f5f9',
		'--secondary-foreground': '#0f172a',
		'--muted': '#f1f5f9',
		'--muted-foreground': '#64748b',
		'--accent': '#f1f5f9',
		'--accent-foreground': '#0f172a',
		'--destructive': '#ef4444',
		'--destructive-foreground': '#f8fafc',
		'--border': '#e2e8f0',
		'--input': '#e2e8f0',
		'--ring': '#0f172a',
		'--success': '#16a34a',
		'--success-foreground': '#f0fdf4',
		'--warning': '#eab308',
		'--warning-foreground': '#fefce8',
		'--info': '#0ea5e9',
		'--info-foreground': '#f0f9ff',
	},
	purple: {
		'--background': '#faf5ff',
		'--foreground': '#3b0764',
		'--card': '#ffffff',
		'--card-foreground': '#3b0764',
		'--popover': '#ffffff',
		'--popover-foreground': '#3b0764',
		'--primary': '#6b21a8',
		'--primary-foreground': '#faf5ff',
		'--secondary': '#f3e8ff',
		'--secondary-foreground': '#581c87',
		'--muted': '#f3e8ff',
		'--muted-foreground': '#7e22ce',
		'--accent': '#f3e8ff',
		'--accent-foreground': '#581c87',
		'--destructive': '#ef4444',
		'--destructive-foreground': '#faf5ff',
		'--border': '#e9d5ff',
		'--input': '#e9d5ff',
		'--ring': '#6b21a8',
		'--success': '#16a34a',
		'--success-foreground': '#f0fdf4',
		'--warning': '#eab308',
		'--warning-foreground': '#fefce8',
		'--info': '#0ea5e9',
		'--info-foreground': '#f0f9ff',
	},
	// Add more themes as needed
};

export type ThemeName = keyof typeof themes;
