import { TTheirStackJobsResponse } from '../types/TTheirStackJobsResponse';

export const TheirStackMockResponse: TTheirStackJobsResponse = {
  metadata: {
    total_results: 2034,
    truncated_results: 0,
    truncated_companies: 0,
    total_companies: 1045,
  },
  data: [
    {
      id: 1234,
      job_title: 'Senior Data Engineer',
      url: 'https://example.com/job/1234',
      date_posted: '2021-01-01',
      has_blurred_data: false,
      company: '…',
      final_url: '…',
      source_url: '…',
      location: '…',
      short_location: '…',
      long_location: '…',
      state_code: '…',
      latitude: 1,
      longitude: 1,
      postal_code: '…',
      remote: true,
      hybrid: true,
      salary_string: '…',
      min_annual_salary: 1,
      min_annual_salary_usd: 1,
      max_annual_salary: 1,
      max_annual_salary_usd: 1,
      avg_annual_salary_usd: 1,
      salary_currency: '…',
      countries: ['…'],
      country: '…',
      cities: ['…'],
      continents: ['…'],
      seniority: 'Mid-Level',
      country_codes: ['…'],
      country_code: '…',
      discovered_at: '2024-10-27T09:12:48.439Z',
      hiring_team: [
        {
          first_name: '…',
          full_name: '…',
          linkedin_url: '…',
          role: '…',
          image_url: '…',
          thumbnail_url: '…',
        },
      ],
      company_domain: '…',
      reposted: false,
      date_reposted: '2024-10-27',
      description: '…',
      company_object: {
        name: 'Google',
        domain: 'google.com',
        industry: 'internet',
        country: 'United States',
        country_code: '…',
        employee_count: 7543,
        logo: 'https://example.com/logo.png',
        num_jobs: 746,
        num_technologies: 746,
        url: 'google.com',
        industry_id: 1,
        linkedin_url: 'http://www.linkedin.com/company/google',
        num_jobs_last_30_days: 34,
        num_jobs_found: 23,
        yc_batch: 'W21',
        apollo_id: '5b839bd0324d4445051f9a5a',
        linkedin_id: '…',
        url_source: '…',
        is_recruiting_agency: true,
        id: '…',
        founded_year: 2019,
        annual_revenue_usd: 189000000,
        annual_revenue_usd_readable: '189M',
        total_funding_usd: 500000,
        last_funding_round_date: '2020-01-01',
        last_funding_round_amount_readable: '$1.2M',
        employee_count_range: '1001-5000',
        long_description:
          'Google is a California-based multinational technology company that offers internet-related services such as a search engine, online advertising and cloud computing.',
        seo_description: '…',
        city: 'Mountain View',
        postal_code: '28040',
        company_keywords: [],
        alexa_ranking: 1,
        publicly_traded_symbol: 'GOOG',
        publicly_traded_exchange: 'NASDAQ',
        investors: ['…'],
        funding_stage: '…',
        has_blurred_data: false,
        technology_slugs: ['kafka', 'elasticsearch'],
        technology_names: ['Kafka', 'Elasticsearch'],
      },
      normalized_title: '…',
      manager_roles: ['…'],
      matching_phrases: [],
      matching_words: [],
    },
    {
      id: 5678,
      job_title: 'Frontend Developer',
      url: 'https://example.com/job/5678',
      date_posted: '2024-03-15',
      has_blurred_data: false,
      company: 'TechCorp',
      final_url: 'https://techcorp.com/careers/frontend-developer',
      source_url: 'https://techcorp.com/careers',
      location: 'New York, NY',
      short_location: 'New York',
      long_location: 'New York, New York, United States',
      state_code: 'NY',
      latitude: 40.7128,
      longitude: -74.006,
      postal_code: '10001',
      remote: false,
      hybrid: true,
      salary_string: '$80,000 - $120,000',
      min_annual_salary: 80000,
      min_annual_salary_usd: 80000,
      max_annual_salary: 120000,
      max_annual_salary_usd: 120000,
      avg_annual_salary_usd: 100000,
      salary_currency: 'USD',
      countries: ['United States'],
      country: 'United States',
      cities: ['New York'],
      continents: ['North America'],
      seniority: 'Mid-Level',
      country_codes: ['US'],
      country_code: 'US',
      discovered_at: '2024-03-16T10:30:00.000Z',
      hiring_team: [
        {
          first_name: 'Jane',
          full_name: 'Jane Smith',
          linkedin_url: 'https://www.linkedin.com/in/janesmith',
          role: 'HR Manager',
          image_url: 'https://example.com/janesmith.jpg',
          thumbnail_url: 'https://example.com/janesmith_thumb.jpg',
        },
      ],
      company_domain: 'techcorp.com',
      reposted: false,
      date_reposted: null,
      description:
        'We are seeking a talented Frontend Developer to join our team...',
      company_object: {
        name: 'TechCorp',
        domain: 'techcorp.com',
        industry: 'Software Development',
        country: 'United States',
        country_code: 'US',
        employee_count: 500,
        logo: 'https://example.com/techcorp_logo.png',
        num_jobs: 25,
        num_technologies: 30,
        url: 'techcorp.com',
        industry_id: 42,
        linkedin_url: 'http://www.linkedin.com/company/techcorp',
        num_jobs_last_30_days: 5,
        num_jobs_found: 3,
        yc_batch: null,
        apollo_id: '5c839bd0324d4445051f9a5b',
        linkedin_id: '1234567',
        url_source: 'company_website',
        is_recruiting_agency: false,
        id: 'TC123',
        founded_year: 2010,
        annual_revenue_usd: 50000000,
        annual_revenue_usd_readable: '50M',
        total_funding_usd: 20000000,
        last_funding_round_date: '2022-06-15',
        last_funding_round_amount_readable: '$10M',
        employee_count_range: '201-500',
        long_description:
          'TechCorp is a leading software development company...',
        seo_description: 'TechCorp - Innovative Software Solutions',
        city: 'New York',
        postal_code: '10001',
        company_keywords: ['software', 'technology', 'innovation'],
        alexa_ranking: 50000,
        publicly_traded_symbol: null,
        publicly_traded_exchange: null,
        investors: ['Acme Ventures', 'Tech Investors LLC'],
        funding_stage: 'Series B',
        has_blurred_data: false,
        technology_slugs: ['react', 'typescript', 'nodejs'],
        technology_names: ['React', 'TypeScript', 'Node.js'],
      },
      normalized_title: 'Frontend Developer',
      manager_roles: ['Engineering Manager', 'CTO'],
      matching_phrases: ['frontend', 'react', 'javascript'],
      matching_words: ['developer', 'web'],
    },
    {
      id: 9101,
      job_title: 'Machine Learning Engineer',
      url: 'https://example.com/job/9101',
      date_posted: '2024-03-10',
      has_blurred_data: false,
      company: 'AI Innovations',
      final_url: 'https://aiinnovations.com/careers/ml-engineer',
      source_url: 'https://aiinnovations.com/careers',
      location: 'San Francisco, CA',
      short_location: 'San Francisco',
      long_location: 'San Francisco, California, United States',
      state_code: 'CA',
      latitude: 37.7749,
      longitude: -122.4194,
      postal_code: '94105',
      remote: true,
      hybrid: false,
      salary_string: '$130,000 - $180,000',
      min_annual_salary: 130000,
      min_annual_salary_usd: 130000,
      max_annual_salary: 180000,
      max_annual_salary_usd: 180000,
      avg_annual_salary_usd: 155000,
      salary_currency: 'USD',
      countries: ['United States'],
      country: 'United States',
      cities: ['San Francisco'],
      continents: ['North America'],
      seniority: 'Senior',
      country_codes: ['US'],
      country_code: 'US',
      discovered_at: '2024-03-11T08:45:00.000Z',
      hiring_team: [
        {
          first_name: 'Alex',
          full_name: 'Alex Johnson',
          linkedin_url: 'https://www.linkedin.com/in/alexjohnson',
          role: 'Head of AI',
          image_url: 'https://example.com/alexjohnson.jpg',
          thumbnail_url: 'https://example.com/alexjohnson_thumb.jpg',
        },
      ],
      company_domain: 'aiinnovations.com',
      reposted: false,
      date_reposted: null,
      description:
        'Join our team of AI experts to develop cutting-edge machine learning models...',
      company_object: {
        name: 'AI Innovations',
        domain: 'aiinnovations.com',
        industry: 'Artificial Intelligence',
        country: 'United States',
        country_code: 'US',
        employee_count: 200,
        logo: 'https://example.com/aiinnovations_logo.png',
        num_jobs: 15,
        num_technologies: 25,
        url: 'aiinnovations.com',
        industry_id: 78,
        linkedin_url: 'http://www.linkedin.com/company/ai-innovations',
        num_jobs_last_30_days: 3,
        num_jobs_found: 2,
        yc_batch: 'S18',
        apollo_id: '5d839bd0324d4445051f9a5c',
        linkedin_id: '7654321',
        url_source: 'company_website',
        is_recruiting_agency: false,
        id: 'AI456',
        founded_year: 2018,
        annual_revenue_usd: 30000000,
        annual_revenue_usd_readable: '30M',
        total_funding_usd: 50000000,
        last_funding_round_date: '2023-09-01',
        last_funding_round_amount_readable: '$25M',
        employee_count_range: '101-200',
        long_description:
          'AI Innovations is at the forefront of artificial intelligence research and development...',
        seo_description: 'AI Innovations - Transforming Industries with AI',
        city: 'San Francisco',
        postal_code: '94105',
        company_keywords: ['AI', 'machine learning', 'deep learning'],
        alexa_ranking: 100000,
        publicly_traded_symbol: null,
        publicly_traded_exchange: null,
        investors: ['Tech Ventures', 'AI Capital'],
        funding_stage: 'Series C',
        has_blurred_data: false,
        technology_slugs: ['python', 'tensorflow', 'pytorch'],
        technology_names: ['Python', 'TensorFlow', 'PyTorch'],
      },
      normalized_title: 'Machine Learning Engineer',
      manager_roles: ['AI Research Director', 'CTO'],
      matching_phrases: ['machine learning', 'AI', 'deep learning'],
      matching_words: ['engineer', 'python'],
    },
    {
      id: 1213,
      job_title: 'DevOps Engineer',
      url: 'https://example.com/job/1213',
      date_posted: '2024-03-18',
      has_blurred_data: false,
      company: 'CloudScale',
      final_url: 'https://cloudscale.com/careers/devops-engineer',
      source_url: 'https://cloudscale.com/careers',
      location: 'Austin, TX',
      short_location: 'Austin',
      long_location: 'Austin, Texas, United States',
      state_code: 'TX',
      latitude: 30.2672,
      longitude: -97.7431,
      postal_code: '78701',
      remote: true,
      hybrid: true,
      salary_string: '$110,000 - $150,000',
      min_annual_salary: 110000,
      min_annual_salary_usd: 110000,
      max_annual_salary: 150000,
      max_annual_salary_usd: 150000,
      avg_annual_salary_usd: 130000,
      salary_currency: 'USD',
      countries: ['United States'],
      country: 'United States',
      cities: ['Austin'],
      continents: ['North America'],
      seniority: 'Mid-Level',
      country_codes: ['US'],
      country_code: 'US',
      discovered_at: '2024-03-19T14:20:00.000Z',
      hiring_team: [
        {
          first_name: 'Sarah',
          full_name: 'Sarah Lee',
          linkedin_url: 'https://www.linkedin.com/in/sarahlee',
          role: 'DevOps Manager',
          image_url: 'https://example.com/sarahlee.jpg',
          thumbnail_url: 'https://example.com/sarahlee_thumb.jpg',
        },
      ],
      company_domain: 'cloudscale.com',
      reposted: false,
      date_reposted: null,
      description:
        'We are looking for a skilled DevOps Engineer to help us scale our cloud infrastructure...',
      company_object: {
        name: 'CloudScale',
        domain: 'cloudscale.com',
        industry: 'Cloud Computing',
        country: 'United States',
        country_code: 'US',
        employee_count: 300,
        logo: 'https://example.com/cloudscale_logo.png',
        num_jobs: 20,
        num_technologies: 35,
        url: 'cloudscale.com',
        industry_id: 56,
        linkedin_url: 'http://www.linkedin.com/company/cloudscale',
        num_jobs_last_30_days: 4,
        num_jobs_found: 3,
        yc_batch: null,
        apollo_id: '5e839bd0324d4445051f9a5d',
        linkedin_id: '9876543',
        url_source: 'company_website',
        is_recruiting_agency: false,
        id: 'CS789',
        founded_year: 2015,
        annual_revenue_usd: 40000000,
        annual_revenue_usd_readable: '40M',
        total_funding_usd: 30000000,
        last_funding_round_date: '2023-02-28',
        last_funding_round_amount_readable: '$15M',
        employee_count_range: '201-500',
        long_description:
          'CloudScale provides scalable cloud infrastructure solutions for businesses of all sizes...',
        seo_description: 'CloudScale - Scalable Cloud Infrastructure Solutions',
        city: 'Austin',
        postal_code: '78701',
        company_keywords: ['cloud', 'devops', 'infrastructure'],
        alexa_ranking: 75000,
        publicly_traded_symbol: null,
        publicly_traded_exchange: null,
        investors: ['Cloud Ventures', 'Tech Growth Fund'],
        funding_stage: 'Series B',
        has_blurred_data: false,
        technology_slugs: ['aws', 'kubernetes', 'terraform'],
        technology_names: ['AWS', 'Kubernetes', 'Terraform'],
      },
      normalized_title: 'DevOps Engineer',
      manager_roles: ['Infrastructure Lead', 'CTO'],
      matching_phrases: ['devops', 'cloud', 'infrastructure'],
      matching_words: ['engineer', 'aws'],
    },
    {
      id: 1415,
      job_title: 'UX/UI Designer',
      url: 'https://example.com/job/1415',
      date_posted: '2024-03-20',
      has_blurred_data: false,
      company: 'DesignWave',
      final_url: 'https://designwave.com/careers/ux-ui-designer',
      source_url: 'https://designwave.com/careers',
      location: 'Seattle, WA',
      short_location: 'Seattle',
      long_location: 'Seattle, Washington, United States',
      state_code: 'WA',
      latitude: 47.6062,
      longitude: -122.3321,
      postal_code: '98101',
      remote: true,
      hybrid: false,
      salary_string: '$90,000 - $130,000',
      min_annual_salary: 90000,
      min_annual_salary_usd: 90000,
      max_annual_salary: 130000,
      max_annual_salary_usd: 130000,
      avg_annual_salary_usd: 110000,
      salary_currency: 'USD',
      countries: ['United States'],
      country: 'United States',
      cities: ['Seattle'],
      continents: ['North America'],
      seniority: 'Mid-Level',
      country_codes: ['US'],
      country_code: 'US',
      discovered_at: '2024-03-21T11:15:00.000Z',
      hiring_team: [
        {
          first_name: 'Michael',
          full_name: 'Michael Chen',
          linkedin_url: 'https://www.linkedin.com/in/michaelchen',
          role: 'Design Director',
          image_url: 'https://example.com/michaelchen.jpg',
          thumbnail_url: 'https://example.com/michaelchen_thumb.jpg',
        },
      ],
      company_domain: 'designwave.com',
      reposted: false,
      date_reposted: null,
      description:
        'Join our creative team to design intuitive and visually appealing user interfaces...',
      company_object: {
        name: 'DesignWave',
        domain: 'designwave.com',
        industry: 'Design',
        country: 'United States',
        country_code: 'US',
        employee_count: 100,
        logo: 'https://example.com/designwave_logo.png',
        num_jobs: 10,
        num_technologies: 15,
        url: 'designwave.com',
        industry_id: 34,
        linkedin_url: 'http://www.linkedin.com/company/designwave',
        num_jobs_last_30_days: 2,
        num_jobs_found: 1,
        yc_batch: null,
        apollo_id: '5f839bd0324d4445051f9a5e',
        linkedin_id: '2468101',
        url_source: 'company_website',
        is_recruiting_agency: false,
        id: 'DW101',
        founded_year: 2017,
        annual_revenue_usd: 15000000,
        annual_revenue_usd_readable: '15M',
        total_funding_usd: 5000000,
        last_funding_round_date: '2022-11-15',
        last_funding_round_amount_readable: '$5M',
        employee_count_range: '51-100',
        long_description:
          'DesignWave is a leading design agency specializing in creating beautiful and functional digital experiences...',
        seo_description: 'DesignWave - Crafting Digital Experiences',
        city: 'Seattle',
        postal_code: '98101',
        company_keywords: ['design', 'UX', 'UI'],
        alexa_ranking: 150000,
        publicly_traded_symbol: null,
        publicly_traded_exchange: null,
        investors: ['Creative Capital', 'Design Accelerator'],
        funding_stage: 'Series A',
        has_blurred_data: false,
        technology_slugs: ['figma', 'sketch', 'adobe-xd'],
        technology_names: ['Figma', 'Sketch', 'Adobe XD'],
      },
      normalized_title: 'UX/UI Designer',
      manager_roles: ['Creative Director', 'Head of Design'],
      matching_phrases: ['UX', 'UI', 'design'],
      matching_words: ['designer', 'creative'],
    },
  ],
};
